sudo: required

language: android
jdk: oraclejdk8

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-25.0.1
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - android-sdk-license-.+
    - android-sdk-preview-license-.+
    - google-gdk-license-.+

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-18 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - touch bintray.properties

script:
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - adb shell input keyevent 82
  - ./gradlew :YaMvp:jacocoTestReport :YaMvp-Rx:jacocoTestReport :YaMvp-Component:connectedCheck

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - xz4214@gmail.com

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
